# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/- task: FortifyOnDemandStatic@8

trigger:
- develop

pool:
  vmImage: ubuntu-latest
steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Bash@3 
  inputs:
    targetType: 'inline'
    script: |
      pwd
      export FTI_TOOLS=sc:22.1.0
      source <(curl -sL https://raw.githubusercontent.com/fortify/FortifyToolsInstaller/latest/FortifyToolsInstaller.sh)

- task: FortifyOnDemandStatic@8

  inputs:
    FortifyProjects: '.'
    ScanCentralLocation: '/home/vsts/.fortify/tools/ScanCentralClient/22.1.0'
    FodConnection: 'Teste Fortify'
    ReleaseOptions: '0'
    ReleaseId: 200003
    EntitlementSelection: '1'
    EntitlementPreference: '0'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '1'
    BuildType: 'mvn'
    PolicyFailAction: '0'
